name: Trigger auto deployment for webgoat

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ develop ]
    paths:
    - '**'
    - '.github/workflows/webgoat-AutoDeployTrigger-9231927f-c8bd-4e91-a263-bfa5073cf004.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'microsoft'
          cache: maven

      - name: Build with Maven Wrapper
        run: ./mvnw -B package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ca2a2d1f10a1acr.azurecr.io
          username: ${{ secrets.WEBGOAT_REGISTRY_USERNAME }}
          password: ${{ secrets.WEBGOAT_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ca2a2d1f10a1acr.azurecr.io/webgoat:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.WEBGOAT_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n webgoat -g webgoat --server ca2a2d1f10a1acr.azurecr.io --username  ${{ secrets.WEBGOAT_REGISTRY_USERNAME }} --password ${{ secrets.WEBGOAT_REGISTRY_PASSWORD }}
            az containerapp update -n webgoat -g webgoat --image ca2a2d1f10a1acr.azurecr.io/webgoat:${{ github.sha }}
